fix(vpn): remove port and add account flag 🌐

diff --git a/bin/.local/bin/vpn b/bin/.local/bin/vpn
--- a/bin/.local/bin/vpn
+++ b/bin/.local/bin/vpn
@@ -12,24 +12,24 @@
 # ░░░░░░░░░░
 
 #█▓▒░  dont run as root
-[ "$(id -u)" -eq 0 ] && echo "just be yourself" && exit 0
+[ "$(id -u)" -eq 0 ] && { echo "just be yourself"; exit 0; }
 
 usage() {
-	cat <<x0
+	me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
+cat <<x0
  _______._____.__________._________
  \\_    (|     /   ._     \\         \\
    \\    l    /    |/     /  /      /
     \\_______/    /l_____X___\\______\\
            \\____/
+ usage: ${me} [-h|-a|-s|-d|-p|-c|-q] host
+   -a|--account  : 1password account alias
+   -s|--secret   : 1password secret item for login
+   -d|--dns      : private ipv4 dns server
+   -p|--protocol : openconnect protocol (default anyconnect)
+   -c|--cert     : pinned tls cert hash
+   -q|--quit     : disconnect vpn and proxy
 x0
-	me="$(basename "$(test -L "$0" && readlink "$0" || echo "$0")")"
-	echo "usage: ${me} [-h|-s|-d|-p|-c|-P|-q] host"
-	echo "  -s|--secret   : 1password secret item for login"
-	echo "  -d|--dns      : private ipv4 dns server"
-	echo "  -p|--protocol : openconnect protocol (default anyconnect)"
-	echo "  -c|--cert     : pinned tls cert hash"
-	echo "  -P|--port     : socks5 proxy port (default 60806)"
-	echo "  -q|--quit     : disconnect vpn and proxy"
 	exit 0
 }
 
@@ -51,10 +51,8 @@ function connect() {
 	dns=$4
 	protocol=$5
 	cert=$6
-	port=$7
-	export INTERNAL_IP4_DNS=$dns
 	[ -z "$cert" ] || cert="--servercert $cert"
-	[ -z "$dns" ] || dns="-d $dns"
+	[ -z "$dns" ] || export INTERNAL_IP4_DNS=$dns
 	echo "starting vpn processes"
 	echo "${login}" | /usr/sbin/openconnect \
 		-b -u "${user}" \
@@ -72,36 +70,37 @@ function disconnect() {
 }
 
 function parse_arguments() {
+	account=''
 	secret=''
 	host=''
 	dns=''
 	protocol='anyconnect'
 	cert=''
-	port='60806'
-	options=$(getopt -o hs:d:p:c:P:q -l help,secret:,dns:,protocol:,cert:,port:,quit -- "$@") || exit 1
+	options=$(getopt -o ha:s:d:p:c:q -l help,account:,secret:,dns:,protocol:,cert:,quit -- "$@") || exit 1
 	set -- $options
 	while [ $# -gt 0 ];do
 		case $1 in
 		-h|--help) usage ;;
+		-a|--account) account="${2//\'/}" ; shift;;
 		-s|--secret) secret="${2//\'/}" ; shift;;
 		-d|--dns) dns="${2//\'/}" ; shift;;
 		-p|--protocol) protocol="${2//\'/}" ; shift;;
 		-c|--cert) cert="${2//\'/}" ; shift;;
-		-P|--port) port="${2//\'/}" ; shift;;
 		-q|--quit) disconnect;;
 		(--) host="${2//\'/}" ; shift; break;;
-		(-*) echo "$0: error - unrecognized option $1" 1>&2; usage;;
+		(-*) echo "vpn error - unrecognized option $1" 1>&2; usage;;
 		(*) break;;
 		esac
 		shift
 	done
 	[ -z "$host" ] && usage
 	[[ "$host" =~ ^(quit|exit|disconnect)$ ]] && disconnect
-    eval $(op signin)
+	[ -z "$account" ] || account="--account ${account}"
+    eval $(op signin ${account})
 	echo "getting credentials"
 	user="$(get_user $secret)"
 	login="$(get_login $secret)"
-	connect "$user" "$login" "$host" "$dns" "$protocol" "$cert" "$port"
+	connect "$user" "$login" "$host" "$dns" "$protocol" "$cert"
 }
 
 # fail fast w/ proper exit codes
